### ISSUE TITLE
level db of spv may some times panic

### ISSUE THREAD

**Issue by RainFallsSilent** [elastos/Elastos.ELA.SPV#49]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x178 pc=0x580f41]

goroutine 53 [running]:
github.com/elastos/Elastos.ELA.SideChain.ID/vendor/github.com/syndtr/goleveldb/leveldb.(*DB).isClosed(...)
/home/zhangbocheng/dev/src/github.com/elastos/Elastos.ELA.SideChain.ID/vendor/github.com/syndtr/goleveldb/leveldb/db_state.go:230
github.com/elastos/Elastos.ELA.SideChain.ID/vendor/github.com/syndtr/goleveldb/leveldb.(*DB).ok(...)
/home/zhangbocheng/dev/src/github.com/elastos/Elastos.ELA.SideChain.ID/vendor/github.com/syndtr/goleveldb/leveldb/db_state.go:235
github.com/elastos/Elastos.ELA.SideChain.ID/vendor/github.com/syndtr/goleveldb/leveldb.(*DB).NewIterator(0x0, 0xc4223043f0, 0x0, 0x0, 0x0)
/home/zhangbocheng/dev/src/github.com/elastos/Elastos.ELA.SideChain.ID/vendor/github.com/syndtr/goleveldb/leveldb/db.go:879 +0x31
github.com/elastos/Elastos.ELA.SideChain.ID/vendor/github.com/elastos/Elastos.ELA.SPV/interface/store.(*queBatch).DelAll(0xc423b36a40, 0xc400026817, 0x0, 0x0)
/home/zhangbocheng/dev/src/github.com/elastos/Elastos.ELA.SideChain.ID/vendor/github.com/elastos/Elastos.ELA.SPV/interface/store/quebatch.go:58 +0x10b
github.com/elastos/Elastos.ELA.SideChain.ID/vendor/github.com/elastos/Elastos.ELA.SPV/interface/store.(*dataBatch).DelAll(0xc423b36a00, 0xc400026817, 0x0, 0x0)
/home/zhangbocheng/dev/src/github.com/elastos/Elastos.ELA.SideChain.ID/vendor/github.com/elastos/Elastos.ELA.SPV/interface/store/databatch.go:69 +0x793
github.com/elastos/Elastos.ELA.SideChain.ID/vendor/github.com/elastos/Elastos.ELA.SPV/interface.(*txBatch).DelTxs(0xc427194320, 0x26817, 0xc427194320, 0x0)
/home/zhangbocheng/dev/src/github.com/elastos/Elastos.ELA.SideChain.ID/vendor/github.com/elastos/Elastos.ELA.SPV/interface/spvservice.go:474 +0x71
github.com/elastos/Elastos.ELA.SideChain.ID/vendor/github.com/elastos/Elastos.ELA.SPV/database.(*defaultChainDB).Rollback(0xc420eaa140, 0xc425eeddc0, 0x29, 0xc423b369e0)
/home/zhangbocheng/dev/src/github.com/elastos/Elastos.ELA.SideChain.ID/vendor/github.com/elastos/Elastos.ELA.SPV/database/defaultdb.go:54 +0xb8
github.com/elastos/Elastos.ELA.SideChain.ID/vendor/github.com/elastos/Elastos.ELA.SPV/blockchain.(*BlockChain).CommitBlock(0xc4201592c0, 0xc4227ab030, 0x26817264a0101, 0xc400000000, 0x0, 0x0)
/home/zhangbocheng/dev/src/github.com/elastos/Elastos.ELA.SideChain.ID/vendor/github.com/elastos/Elastos.ELA.SPV/blockchain/blockchain.go:120 +0x675
github.com/elastos/Elastos.ELA.SideChain.ID/vendor/github.com/elastos/Elastos.ELA.SPV/sync.(*SyncManager).handleBlockMsg(0xc420079680, 0xc423b36720)
/home/zhangbocheng/dev/src/github.com/elastos/Elastos.ELA.SideChain.ID/vendor/github.com/elastos/Elastos.ELA.SPV/sync/manager.go:360 +0x1f9
github.com/elastos/Elastos.ELA.SideChain.ID/vendor/github.com/elastos/Elastos.ELA.SPV/sync.(*SyncManager).blockHandler(0xc420079680)
/home/zhangbocheng/dev/src/github.com/elastos/Elastos.ELA.SideChain.ID/vendor/github.com/elastos/Elastos.ELA.SPV/sync/manager.go:610 +0x29e
created by github.com/elastos/Elastos.ELA.SideChain.ID/vendor/github.com/elastos/Elastos.ELA.SPV/sync.(*SyncManager).Start
/home/zhangbocheng/dev/src/github.com/elastos/Elastos.ELA.SideChain.ID/vendor/github.com/elastos/Elastos.ELA.SPV/sync/manager.go:716 +0x59

**Comment by RainFallsSilent** [comment]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x178 pc=0x580f41]

goroutine 53 [running]:
github.com/elastos/Elastos.ELA.SideChain.ID/vendor/github.com/syndtr/goleveldb/leveldb.(*DB).isClosed(...)
        /home/zhangbocheng/dev/src/github.com/elastos/Elastos.ELA.SideChain.ID/vendor/github.com/syndtr/goleveldb/leveldb/db_state.go:230
github.com/elastos/Elastos.ELA.SideChain.ID/vendor/github.com/syndtr/goleveldb/leveldb.(*DB).ok(...)
        /home/zhangbocheng/dev/src/github.com/elastos/Elastos.ELA.SideChain.ID/vendor/github.com/syndtr/goleveldb/leveldb/db_state.go:235
github.com/elastos/Elastos.ELA.SideChain.ID/vendor/github.com/syndtr/goleveldb/leveldb.(*DB).NewIterator(0x0, 0xc4223043f0, 0x0, 0x0, 0x0)
        /home/zhangbocheng/dev/src/github.com/elastos/Elastos.ELA.SideChain.ID/vendor/github.com/syndtr/goleveldb/leveldb/db.go:879 +0x31
github.com/elastos/Elastos.ELA.SideChain.ID/vendor/github.com/elastos/Elastos.ELA.SPV/interface/store.(*queBatch).DelAll(0xc423b36a40, 0xc400026817, 0x0, 0x0)
        /home/zhangbocheng/dev/src/github.com/elastos/Elastos.ELA.SideChain.ID/vendor/github.com/elastos/Elastos.ELA.SPV/interface/store/quebatch.go:58 +0x10b
github.com/elastos/Elastos.ELA.SideChain.ID/vendor/github.com/elastos/Elastos.ELA.SPV/interface/store.(*dataBatch).DelAll(0xc423b36a00, 0xc400026817, 0x0, 0x0)
        /home/zhangbocheng/dev/src/github.com/elastos/Elastos.ELA.SideChain.ID/vendor/github.com/elastos/Elastos.ELA.SPV/interface/store/databatch.go:69 +0x793
github.com/elastos/Elastos.ELA.SideChain.ID/vendor/github.com/elastos/Elastos.ELA.SPV/interface.(*txBatch).DelTxs(0xc427194320, 0x26817, 0xc427194320, 0x0)
        /home/zhangbocheng/dev/src/github.com/elastos/Elastos.ELA.SideChain.ID/vendor/github.com/elastos/Elastos.ELA.SPV/interface/spvservice.go:474 +0x71
github.com/elastos/Elastos.ELA.SideChain.ID/vendor/github.com/elastos/Elastos.ELA.SPV/database.(*defaultChainDB).Rollback(0xc420eaa140, 0xc425eeddc0, 0x29, 0xc423b369e0)
        /home/zhangbocheng/dev/src/github.com/elastos/Elastos.ELA.SideChain.ID/vendor/github.com/elastos/Elastos.ELA.SPV/database/defaultdb.go:54 +0xb8
github.com/elastos/Elastos.ELA.SideChain.ID/vendor/github.com/elastos/Elastos.ELA.SPV/blockchain.(*BlockChain).CommitBlock(0xc4201592c0, 0xc4227ab030, 0x26817264a0101, 0xc400000000, 0x0, 0x0)
        /home/zhangbocheng/dev/src/github.com/elastos/Elastos.ELA.SideChain.ID/vendor/github.com/elastos/Elastos.ELA.SPV/blockchain/blockchain.go:120 +0x675
github.com/elastos/Elastos.ELA.SideChain.ID/vendor/github.com/elastos/Elastos.ELA.SPV/sync.(*SyncManager).handleBlockMsg(0xc420079680, 0xc423b36720)
        /home/zhangbocheng/dev/src/github.com/elastos/Elastos.ELA.SideChain.ID/vendor/github.com/elastos/Elastos.ELA.SPV/sync/manager.go:360 +0x1f9
github.com/elastos/Elastos.ELA.SideChain.ID/vendor/github.com/elastos/Elastos.ELA.SPV/sync.(*SyncManager).blockHandler(0xc420079680)
        /home/zhangbocheng/dev/src/github.com/elastos/Elastos.ELA.SideChain.ID/vendor/github.com/elastos/Elastos.ELA.SPV/sync/manager.go:610 +0x29e
created by github.com/elastos/Elastos.ELA.SideChain.ID/vendor/github.com/elastos/Elastos.ELA.SPV/sync.(*SyncManager).Start
        /home/zhangbocheng/dev/src/github.com/elastos/Elastos.ELA.SideChain.ID/vendor/github.com/elastos/Elastos.ELA.SPV/sync/manager.go:716 +0x59

**Comment by RainFallsSilent** [comment]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x178 pc=0x580f41]

goroutine 53 [running]:
github.com/elastos/Elastos.ELA.SideChain.ID/vendor/github.com/syndtr/goleveldb/leveldb.(*DB).isClosed(...)
        /home/zhangbocheng/dev/src/github.com/elastos/Elastos.ELA.SideChain.ID/vendor/github.com/syndtr/goleveldb/leveldb/db_state.go:230
github.com/elastos/Elastos.ELA.SideChain.ID/vendor/github.com/syndtr/goleveldb/leveldb.(*DB).ok(...)
        /home/zhangbocheng/dev/src/github.com/elastos/Elastos.ELA.SideChain.ID/vendor/github.com/syndtr/goleveldb/leveldb/db_state.go:235
github.com/elastos/Elastos.ELA.SideChain.ID/vendor/github.com/syndtr/goleveldb/leveldb.(*DB).NewIterator(0x0, 0xc4223043f0, 0x0, 0x0, 0x0)
        /home/zhangbocheng/dev/src/github.com/elastos/Elastos.ELA.SideChain.ID/vendor/github.com/syndtr/goleveldb/leveldb/db.go:879 +0x31
github.com/elastos/Elastos.ELA.SideChain.ID/vendor/github.com/elastos/Elastos.ELA.SPV/interface/store.(*queBatch).DelAll(0xc423b36a40, 0xc400026817, 0x0, 0x0)
        /home/zhangbocheng/dev/src/github.com/elastos/Elastos.ELA.SideChain.ID/vendor/github.com/elastos/Elastos.ELA.SPV/interface/store/quebatch.go:58 +0x10b
github.com/elastos/Elastos.ELA.SideChain.ID/vendor/github.com/elastos/Elastos.ELA.SPV/interface/store.(*dataBatch).DelAll(0xc423b36a00, 0xc400026817, 0x0, 0x0)
        /home/zhangbocheng/dev/src/github.com/elastos/Elastos.ELA.SideChain.ID/vendor/github.com/elastos/Elastos.ELA.SPV/interface/store/databatch.go:69 +0x793
github.com/elastos/Elastos.ELA.SideChain.ID/vendor/github.com/elastos/Elastos.ELA.SPV/interface.(*txBatch).DelTxs(0xc427194320, 0x26817, 0xc427194320, 0x0)
        /home/zhangbocheng/dev/src/github.com/elastos/Elastos.ELA.SideChain.ID/vendor/github.com/elastos/Elastos.ELA.SPV/interface/spvservice.go:474 +0x71
github.com/elastos/Elastos.ELA.SideChain.ID/vendor/github.com/elastos/Elastos.ELA.SPV/database.(*defaultChainDB).Rollback(0xc420eaa140, 0xc425eeddc0, 0x29, 0xc423b369e0)
        /home/zhangbocheng/dev/src/github.com/elastos/Elastos.ELA.SideChain.ID/vendor/github.com/elastos/Elastos.ELA.SPV/database/defaultdb.go:54 +0xb8
github.com/elastos/Elastos.ELA.SideChain.ID/vendor/github.com/elastos/Elastos.ELA.SPV/blockchain.(*BlockChain).CommitBlock(0xc4201592c0, 0xc4227ab030, 0x26817264a0101, 0xc400000000, 0x0, 0x0)
        /home/zhangbocheng/dev/src/github.com/elastos/Elastos.ELA.SideChain.ID/vendor/github.com/elastos/Elastos.ELA.SPV/blockchain/blockchain.go:120 +0x675
github.com/elastos/Elastos.ELA.SideChain.ID/vendor/github.com/elastos/Elastos.ELA.SPV/sync.(*SyncManager).handleBlockMsg(0xc420079680, 0xc423b36720)
        /home/zhangbocheng/dev/src/github.com/elastos/Elastos.ELA.SideChain.ID/vendor/github.com/elastos/Elastos.ELA.SPV/sync/manager.go:360 +0x1f9
github.com/elastos/Elastos.ELA.SideChain.ID/vendor/github.com/elastos/Elastos.ELA.SPV/sync.(*SyncManager).blockHandler(0xc420079680)
        /home/zhangbocheng/dev/src/github.com/elastos/Elastos.ELA.SideChain.ID/vendor/github.com/elastos/Elastos.ELA.SPV/sync/manager.go:610 +0x29e
created by github.com/elastos/Elastos.ELA.SideChain.ID/vendor/github.com/elastos/Elastos.ELA.SPV/sync.(*SyncManager).Start
        /home/zhangbocheng/dev/src/github.com/elastos/Elastos.ELA.SideChain.ID/vendor/github.com/elastos/Elastos.ELA.SPV/sync/manager.go:716 +0x59

**Comment by alexpan0610** [comment]
Fix on https://github.com/elastos/Elastos.ELA.SPV/pull/50
